#!/usr/bin/env node
// hub-core/generate.mjs — генератор ЯДРА ХАБА воркспейса (briefs/hub-core-design.md).
//
// Модель: хаб = тонкий менеджер воркспейса (не продукт). Ядро = реестр + дверь + канал.
// Этот скрипт — «реестр → дверь»: сканит omnifield.yaml всех продуктов воркспейса →
// валидирует Zod'ом (@omnifield/contract-manifest, полная проверка вкл. superRefine) →
// строит реестр → ГЕНЕРИТ stacks/gateway/nginx.conf (маршруты) + stacks/gateway/hub/
// index.html (лендинг). Рукописного nginx/лендинга больше нет; products.md ретайрится.
//
//   node generate.mjs           — пишет сгенерённые файлы
//   node generate.mjs --check   — не пишет; exit 1 при дрейфе (шаг CI: «регенери»)
//
// Канал (docker-ops) — Portainer, отдельно (Р1). Здесь — только реестр+дверь.

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseYaml } from "yaml";
import { ProductManifest } from "@omnifield/contract-manifest";

const HERE = dirname(fileURLToPath(import.meta.url));
const DEVOPSER = resolve(HERE, "..");
const WORKSPACE = resolve(DEVOPSER, ".."); // /workspaces — все продукты сиблингами
const GW = join(DEVOPSER, "stacks", "gateway");
const NGINX_OUT = join(GW, "nginx.conf");
const LANDING_OUT = join(GW, "hub", "index.html");

const check = process.argv.includes("--check");

const esc = (s) =>
  String(s ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]);

// --- 1. Реестр: скан + валидация манифестов -------------------------------
function buildRegistry() {
  const registry = [];
  const skipped = [];
  for (const e of readdirSync(WORKSPACE, { withFileTypes: true })) {
    if (!e.isDirectory()) continue;
    const p = join(WORKSPACE, e.name, "omnifield.yaml");
    if (!existsSync(p)) continue;
    let raw;
    try {
      raw = parseYaml(readFileSync(p, "utf8"));
    } catch (err) {
      skipped.push(`${e.name}: YAML не парсится — ${err.message}`);
      continue;
    }
    const res = ProductManifest.safeParse(raw);
    if (!res.success) {
      const why = res.error.issues
        .map((i) => `${i.path.join(".") || "<root>"}: ${i.message}`)
        .join("; ");
      skipped.push(`${e.name}: манифест невалиден — ${why}`);
      continue;
    }
    registry.push({ repo: e.name, m: res.data });
  }
  registry.sort((a, b) => a.m.name.localeCompare(b.m.name));
  return { registry, skipped };
}

// --- 2. Дверь: nginx.conf из реестра --------------------------------------
// upstream = <alias>:<port>, alias = имя продукта (docker network-alias = имя репо =
// manifest.name). resolver → runtime-резолв (gateway стартует без поднятых продуктов).
function genNginx(registry) {
  const locs = [];
  for (const { m } of registry) {
    if (!m.reach) continue;
    for (const r of m.reach.routes) {
      const v = `$up_${m.name.replace(/-/g, "_")}_${r.port}`;
      locs.push(
        `    # ${m.name} (${m.type}) → ${m.name}:${r.port}\n` +
          `    location ${r.path} {\n` +
          `        set ${v} ${m.name};\n` +
          `        proxy_pass http://${v}:${r.port};\n` +
          `        proxy_http_version 1.1;\n` +
          `        proxy_set_header Upgrade $http_upgrade;\n` +
          `        proxy_set_header Connection $connection_upgrade;\n` +
          `        proxy_set_header Host $host;\n` +
          `        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n` +
          `        proxy_set_header X-Forwarded-Proto $scheme;\n` +
          `        proxy_buffering off;\n` +
          `        proxy_read_timeout 1h;\n` +
          `    }`,
      );
    }
  }
  return (
    `# GENERATED by hub-core (devopser/hub-core/generate.mjs) — НЕ править руками.\n` +
    `# Источник — omnifield.yaml продуктов воркспейса. Регенерация: pnpm -C hub-core generate.\n` +
    `# Single-origin: наружу только :8080, апстримы по docker-сети omnifield-gateway\n` +
    `# (alias = имя продукта). resolver → runtime-резолв (gateway стартует без продуктов).\n\n` +
    `resolver 127.0.0.11 valid=10s ipv6=off;\n\n` +
    `# ws/HMR-safe: upgrade на ws-запрос, close иначе (vite HMR + обычные/SSE).\n` +
    `map $http_upgrade $connection_upgrade {\n    default upgrade;\n    ''      close;\n}\n\n` +
    `server {\n    listen 80;\n    server_name _;\n    charset utf-8;\n\n` +
    `    root /usr/share/nginx/html;\n    index index.html;\n\n` +
    `${locs.join("\n\n")}\n}\n`
  );
}

// --- 3. Лендинг: карточки продуктов из реестра ----------------------------
function genLanding(registry) {
  const cards = registry
    .map(({ m }) => {
      const href = m.reach?.routes[0]?.path ?? "#";
      const tag = m.reach ? m.type : `${m.type} · headless`;
      return (
        `      <a class="card" href="${esc(href)}">\n` +
        `        <h2>${esc(m.title ?? m.name)}</h2>\n` +
        `        <p class="tag">${esc(tag)}</p>\n` +
        `        <p class="desc">${esc(m.description ?? "")}</p>\n` +
        `        <code>${esc(href)}</code>\n` +
        `      </a>`
      );
    })
    .join("\n");
  return `<!doctype html>
<html lang="ru">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Omnifield — воркспейс</title>
<style>
  :root { color-scheme: light dark; --bg:#0d1117; --fg:#e6edf3; --card:#161b22; --br:#30363d; --acc:#58a6ff; }
  * { box-sizing:border-box; } body { margin:0; font:16px/1.5 system-ui,sans-serif; background:var(--bg); color:var(--fg); }
  header { padding:2.5rem 1.5rem 1rem; } header h1 { margin:0; font-size:1.8rem; } header p { margin:.3rem 0 0; opacity:.6; }
  main.grid { display:grid; gap:1rem; grid-template-columns:repeat(auto-fill,minmax(240px,1fr)); padding:1.5rem; max-width:1100px; }
  .card { display:block; padding:1.1rem 1.2rem; background:var(--card); border:1px solid var(--br); border-radius:12px; text-decoration:none; color:inherit; transition:border-color .15s; }
  .card:hover { border-color:var(--acc); }
  .card h2 { margin:0 0 .2rem; font-size:1.15rem; } .tag { margin:0; font-size:.78rem; text-transform:uppercase; letter-spacing:.05em; opacity:.55; }
  .desc { margin:.5rem 0 .7rem; opacity:.85; font-size:.92rem; } .card code { font-size:.82rem; color:var(--acc); }
  footer { padding:1rem 1.5rem 2.5rem; opacity:.4; font-size:.8rem; }
</style>
</head>
<body>
  <header><h1>Omnifield</h1><p>Воркспейс · ${registry.length} продукт(ов) · единая дверь :8080</p></header>
  <main class="grid">
${cards}
  </main>
  <footer>GENERATED hub-core — реестр из omnifield.yaml. Канал (ops) — Portainer.</footer>
</body>
</html>
`;
}

// --- main -----------------------------------------------------------------
const { registry, skipped } = buildRegistry();
for (const s of skipped) console.warn(`[hub-core] ⚠ пропущен ${s}`);
if (!registry.length) {
  console.error("[hub-core] ✖ ни одного валидного манифеста в воркспейсе — нечего генерить.");
  process.exit(1);
}

const nginx = genNginx(registry);
const landing = genLanding(registry);

if (check) {
  let drift = false;
  for (const [path, gen] of [
    [NGINX_OUT, nginx],
    [LANDING_OUT, landing],
  ]) {
    const cur = existsSync(path) ? readFileSync(path, "utf8") : null;
    if (cur !== gen) {
      console.error(`[hub-core] ДРЕЙФ: ${path} расходится с манифестами — прогони generate.`);
      drift = true;
    }
  }
  process.exit(drift ? 1 : 0);
}

mkdirSync(dirname(LANDING_OUT), { recursive: true });
writeFileSync(NGINX_OUT, nginx);
writeFileSync(LANDING_OUT, landing);
console.log(`[hub-core] реестр (${registry.length}): ${registry.map((r) => r.m.name).join(", ")}`);
if (skipped.length) console.log(`[hub-core] пропущено: ${skipped.length}`);
console.log(`[hub-core] сгенерено:\n  ${NGINX_OUT}\n  ${LANDING_OUT}`);
